//                      En esta seccion colocaremos todos los ID de nuestros (en este caso) juegos con susrespectivos desarrolladores y una descripcion del mismo

const games = [
  
  
  //                                                                             PlayStation2

  {id: 1, name: "God of War", price: 500, developer: "SCE Santa Monica Studio", image: "godofwar.png", category: "PlayStation 2", description: "Es uno de los más espectaculares y frenéticos juegos de acción en PlayStation 2. Recogiendo el testigo de títulos como Devil May Cry, nos lleva a una antigua Grecia sumida en el caos entre atenieses, persas y la ira de los antiguos dioses. Nosotros seremos Kratos, un general espartano que ha ejercido de soldado de los dioses, pero que ahora se revela contra ellos. Acción frenética y algún que otro puzle en uno de los juegos de acción con mayúsculas de PlayStation2." },
  {id: 2, name: "Devil May Cry", price: 500, developer: "Capcom", image: "devilmaycry.png", category: "PlayStation 2", description: "El mundo del videojuego tiene un nuevo héroe de acción: Dante, un cazador de demonios, hijo de Sparda, que lucha contra el mal para vengar la muerte de su madre."},
  {id: 3, name: "Grand Theft Auto", price: 800, developer: "RockStar Games", image: "gtasan.png", category: "PlayStation 2", description: "La trama del juego ocurre en San Andreas, estado ficticio que contiene a tres ciudades metropolitanas: Los Santos, San Fierro y Las Venturas; las tres basadas en las ciudades de Los Ángeles, San Francisco y Las Vegas, respectivamente, siendo el segundo mapa más extenso de la saga detrás de GTA V. Ambientado en 1992, la obra cuenta la historia de Carl Johnson “CJ”, quien decide volver a Los Santos tras cinco años de haberse ausentado en Liberty City —ciudad de otros videojuegos de la saga como GTA III, GTA Liberty City Stories o GTA IV— después de enterarse del asesinato de su madre. Al llegar, CJ intenta restablecer el poder de su antigua banda y su familia, mientras desvela poco a poco la verdad detrás de la muerte de su madre. Su trama se basa libremente en sucesos como la rivalidad entre las pandillas Bloods y Crips, la epidemia de crack, el escándalo Rampart y los disturbios de Los Ángeles de 1992."},
  {id: 4, name: "Medal of Honor Frontline", price: 500, developer: "Electronic Arts", image: "medalofhonor.png", category: "PlayStation 2", description: "Participar en el desembarco de Normandía del 6 de junio de 1944, el teniente James Patterson es reclutado por la OSS (Office Strategy States) y comisionado para llevar a cabo algunas misiones de espionaje y sabotaje. La primera consiste en infiltrarse en un sistema de fabricación de Submarinos en la Francia ocupada para tratar de dar un golpe importante a las líneas de producción de submarinos que amenaza a la flota aliada del Atlántico. Posteriormente Patterson es enviado a Holanda en la víspera de la operación Market Garden para reunirse con algunos miembros de la resistencia local y rescatar a Franz Gerritt, un guerrillero que está al tanto de alguna información acerca de un nuevo caza alemán que sería objeto de estudio."},
  {id: 5, name: "Sniper Elite", price: 500, developer: "Rebellion Developments", image: "sniperelite.png", category: "PlayStation 2", description: "El videojuego transcurre en Berlín, a finales de la segunda guerra mundial. El personaje principal del juego es un francotirador estadounidense de la organización secreta OSS, que se infiltra al ejército alemán, pero su objetivo es evitar que los rusos descubran la bomba atómica alemana, además de eliminar oficiales del NKVD (comisarios políticos de Ejército rojo) y altos oficiales del estado mayor de Hitler, como Martin Bormann."},
  {id: 6, name: "Call of Duty World at War", price: 500, developer: "Rebellion Developments", image: "cod.png", category: "PlayStation 2", description: "La campaña estadounidense sigue al Soldado Joe Miller y al equipo igual al del World at War original, sin embargo, Miller en este título pertenece a la 2ª División de la Infantería de la Marina, en vez de la 1ª. En la campaña de Europa occidental, el jugador asume a Lucas Gibson, soldado de la 80ª División de Infantería estadounidense. Las misiones tienen como ambiente a Luxemburgo y Austria. En la mayor parte de la campaña de Europa, el jugador asume el rol del Soldado Tom Sharpe, de la 6ª División Aerotransportada británica."},
  {id: 7, name: "Grand Theft Auto Liberty City Stories", price: 4, developer: "RockStar Games", image: "gtalc.png", category: "PlayStation 2", description: "El protagonista del juego es Toni Cipriani, un mafioso que ha estado escondido 4 años, por haber asesinado a otro importante mafioso, y vuelve a su ciudad, a Liberty City, en el año 1998 (ciudad donde se desarrolla otro juego de la saga, Grand Theft Auto III, pero en el año 2001). Toni no puede ir ni a Staunton Island ni a Shoreside Vale de momento, ya que los constructores y los que controlan el ferry están en huelga y los puentes están desarmados. Después de la misión 'Driving Mr. Leone' Toni podrá acceder a Staunton Island por el carril de la derecha de Callahan Point, que estará roto el resto del juego pero se podrá usar igual, o por el ferry (25$). Aún así los huelguistas no dejarán pasar a nadie a Shoreside Vale, y el puente estará desarmado. Luego de la misión Love on the Rocks, Toni podrá pasar a Shoreside Vale. Algo muy importante es saber que el juego se desarrolla en 1998, pero antes de mayo de ese año."},
  {id: 8, name: "Resident Evil 4", price: 800, developer: "Capcom", image: "re4.png", category: "PlayStation 2", description: "El argumento del juego nos pone en la piel de Leon Scott Kennedy, sobreviviente del desastre vírico que destruyó a Raccoon City, convertido ahora seis años después de este suceso en un agente del Servicio Secreto de los Estados Unidos enviado a una zona rural de España con la misión de rescatar a la hija del Presidente de los Estados Unidos, Ashley Graham que fuera secuestrada por una secta que opera en la zona. La investigación de Leon se complica luego de que una horda de aldeanos enfurecidos lo ataquen sin razón aparente."},
  {id: 9, name: "Metal Gear Solid 3", price: 800, developer: "Konami", image: "metalgear.png", category: "PlayStation 2", description: "La URSS mantiene retenido a Nikolai Stepanovich Sokolov, un ingeniero que trabaja en una nueva arma súper secreta, que daría una superioridad técnica frente a EE. UU., lo que podría provocar el final de la Guerra Fría y empezar una guerra verdadera, la Tercera Guerra Mundial. Para evitar esto, el Gobierno estadounidense envía a Jack, un joven agente de la recién creada unidad FOX, especialista en misiones de infiltración."},
  {id: 10, name: "Mortal Kombat Armagedon", price: 700, developer: "Midway Games & Kung Fu Factory", image: "mkarmagedon.png", category: "PlayStation 2", description: "La historia de este título se basa alrededor de una épica batalla final entre todos los más poderosos luchadores de todos los reinos que ha sido provocada por el exceso de poder entre ellos. Involucra a todos los luchadores aparecidos en algún anterior Mortal Kombat e incluye a dos nuevos que son claves para entender la trama: Taven y Daegon. Ambos hermanos se ven envueltos en una búsqueda del tesoro creada por sus padres Argus, el Dios Protector de Edenia y Delia, una poderosa vidente quien ha predicho que el exceso de poder de los guerreros destruirá todos los reinos conocidos. Ellos son entregados al cuidado de Orin y Caro, dos dragones que deberán despertarlos a ambos miles de años después, poco tiempo antes de que ocurra esta batalla final ya que uno de ellos dos será el destinado a ser el victorioso. Ante el conocimiento de este futuro y con el destino de los hermanos ya escrito, los Dioses Antiguos ordenan la creación de Blaze, un elemental de fuego cuya finalidad será provocar el Armagedón."},
  {id: 11, name: "Bully", price: 800, developer: "RockStar Games", image: "bully.png", category: "PlayStation 2", description: "El juego comienza presentándonos a nuestro pequeño y rudo Jimmy Hopkins, su objetivo es sobrevivir un año en la Academia Bullworth, un internado que alberga snobs de élite y grupos de delincuentes que, como Jimmy, no serían aceptados en ningún otro lugar. Afortunadamente para nosotros, Jimmy no está satisfecho con la mera supervivencia, y cuanto más tiempo pasa en Bullworth, más cansado está con su cultura de intimidación y luchas de poder idiotas entre las cinco camarillas de la escuela. No pasa mucho tiempo antes de que decida tomar el asunto en sus propias manos, primero tratando de encajar con cada una de las camarillas y, cuando eso no funciona, golpeándolas salvajemente hasta que lo reconozcan como su líder."},
  {id: 12, name: "Black", price: 600, developer: "Criterion Games", image: "black.png", category: "PlayStation 2", description: "La historia en Black es un tanto superficial y está contada a modo de flashbacks, en un interrogatorio entre un alto cargo del gobierno y el soldado protagonista de la acción. Las cinemáticas de este interrogatorio son de imagen real, con un estilo que recuerda al de series como CSI, siendo bastante llamativos, aunque el juego no hace en absoluto hincapié en la historia. Estas cinemáticas intentan maquillar la completa ausencia de historia en el juego, algo de lo que Criterion había advertido al decir que se iba a centrar únicamente en la acción."},

  //                                                                            Nintendo Switch

  {id: 13, name: "Dead Cells", price: 1250, developer: "Sebastien Bénard", image: "deadcell.png", category: "Nintendo Switch", description: "El estudio nos trae Dead Cells, trasladándonos a un reino que ha caído en desgracia por culpa de algún tipo de maldición o enfermedad que hizo que nuestro protagonista, conocido como “el prisionero”, volviese a la vida cada vez que fuese ejecutado. La historia del juego no se nos aclara en casi ningún momento, pero podremos encontrar algún que otro dato escondido en las distintas mazmorras que nos permitirá hacer nuestras propias elucubraciones sobre lo ocurrido."},
  {id: 14, name: "Immortals Fenyx Rising", price: 1100, developer: "Ubisoft", image: "ifr.png", category: "Nintendo Switch", description: "La acción transcurre en una Antigua Grecia llena de elementos mitológicos, dioses y titanes. Zeus y Prometeo -el titán castigado por robar el fuego- narran la historia de Fenyx, un simple mortal que naufraga en la Isla Áurea y se convierte en el elegido para derrotar al malvado Tifón"},
  {id: 15, name: "Overcooked 2", price: 750, developer: "Team17", image: "overc.png", category: "Nintendo Switch", description: "Overcooked vuelve con un nuevo y caótico juego de cocina en acción! Regresa al Reino de la Cebolla y organiza tu equipo de chefs en un cooperativo clásico o en partidas en línea de hasta cuatro jugadores. Agarraos los delantales... es hora de salvar el mundo (¡otra vez!)"},
  {id: 16, name: "Captain toad treasure tracker", price: 1200, developer: "Nintendo", image: "toad.png", category: "Nintendo Switch", description: "Capitán Toad y Toadette están a la caza de un tesoro, deben escalar una estructura para obtener un Estrella de Poder. Pronto después caen del cielo Wingo, un pájaro grande que se ha descrito como un amante de todas las cosas brillantes, agarra la estrella. Toadette intenta recuperarla mientras el Capitán Toad se cae temporalmente. Wingo se lleva la estrella y a Toadette dejando al capitán por su cuenta. Capitán toad debe luego pasar por los niveles recogiendo Estrellas para luchar contra Wingo y rescatar finalmente a Toadette."},
  {id: 17, name: "Crash Bandicoot Remastered Collection", price: 1500, developer: "Vicarious Visions", image: "crash.png", category: "Nintendo Switch", description: "¿Qué incluye Crash Bandicoot n sane Trilogy?Sane Trilogy incluye Crash Bandicoot, Crash Bandicoot 2: Cortex Strikes Back y Crash Bandicoot 3: Warped, que se recrearon de cero y con mucho amor. Los gráficos y sonidos nuevos permiten traer la jugabilidad clásica de la serie a toda una nueva generación."},
  {id: 18, name: "The Legend of Zelda: Breath of the wild", price: 1800, developer: "Nintendo Entertainment Planning & Development", image: "zelda.png", category: "Nintendo Switch", description: "La trama de Breath of the Wild arranca con un joven Link que despierta de un largo sueño amnésico y sin recuerdos del mundo en el que está. Gracias a una extraña tecnología Sheikah es capaz de comunicarse y aprender más sobre la extraña tierra de Hyrule, y se lanza a una aventura que cambiará su vida (y su mundo) para siempre. En esta ocasión, Link será un personaje mucho más real y con un comportamiento más humano, que reaccionará a aspectos como el clima, los enemigos, tendrá que buscar fuentes de calor, ropa, armas..."},
  {id: 19, name: "Minecraft", price: 2400, developer: "MoJang", image: "minecraft.png", category: "Nintendo Switch", description: "Minecraft es un videojuego de construcción de tipo «mundo abierto» o sandbox creado originalmente por el sueco Markus Persson, y posteriormente desarrollado por Mojang Studios"},
  {id: 20, name: "Mortal Kombat 11", price: 1300, developer: "NetherRealm Studios", image: "mk11.png", category: "Nintendo Switch", description: "Tras la derrota de Shinnok, Raiden se ve forzado a absorber toda la corrupción y maldad lanzadas por el Dios caído que infectaron la esencia de la cámara Jinsei para poder restaurarla, provocando su transformación en su versión corrompida, volviéndose completamente despiadado, asegurándose de eliminar a cualquiera que considere una amenaza contra el reino de la Tierra antes de que actúe siendo capaz incluso de utilizar el amuleto de Shinnok para aumentar su poder. Lo primero que hace Raiden en este estado es decapitar a Shinnok, no sin antes torturarlo lo suficiente. Al decapitar a Shinnok, Kronika, la guardiana del tiempo hace su aparición advirtiendo que todo lo que el Raiden de esta línea temporal ocasionó, provocó su intervención; al tiempo que revela su identidad como la madre de Shinnok, advierte que alterará la historia para detener a Raiden."},
  {id: 21, name: "Just Dance 2021", price: 2000, developer: "Ubisoft", image: "justd.png", category: "Nintendo Switch", description: "Just Dance® 2021 es el mayor juego de baile con 40 increíbles éxitos de las listas de popularidad como Dont Start Now de Dua Lipa, Feel Special de TWICE, y Señorita de Shawn Mendes y Camila Cabello. ¡Comienza una fiesta de baile que pueden disfrutar tu familia y tus amigos!"},
  {id: 22, name: "Aragimi", price: 650, developer: "Lince Works", image: "aragami.png", category: "Nintendo Switch", description: "Yato es un dios menor que sueña con tener una gran cantidad de seguidores que lo adoren y recen plegarias por él. Desafortunadamente, su sueño está lejos de hacerse realidad, debido a que no tiene ni siquiera un solo santuario dedicado a su persona."},
  {id: 23, name: "New Super Mario Bros", price: 3500, developer: "Nintendo Entertainment Analysis and Development", image: "mariodeluxe.png", category: "Nintendo Switch", description: "Es la primera entrega de la subserie New Super Mario Bros. de la franquicia, y sigue a Mario mientras se abre camino a través de los secuaces de Bowser para rescatar a la Princesa Peach."},
  {id: 24, name: "Spyro!", price: 1500, developer: "Toys for Bob", image: "spyro.png", category: "Nintendo Switch", description: "Al igual que en los videojuegos originales, el protagonista es Spyro, un pequeño dragón morado que cuenta con habilidades como escupir fuego, saltar y volar, que le permiten enfrentarse en diversas aventuras contra Gnasty Gnorc, Ripto y La Hechicera, aunque hay otros personajes jugables como Sheila y Cazador."},

  //                                                                              PlayStation 3

  {id: 25, name: "L.A. Noire", price: 1899, developer: "RockStar Games", image: "la.png", category: "PlayStation 3", description: "La trama se centra en Cole Phelps, un exmarine que tras la Segunda Guerra Mundial comienza a trabajar como agente del Departamento de Policía de Los Ángeles como agente de patrulla junto a su compañero Ralph Dunn."},
  {id: 26, name: "Rayman Origins", price: 1200, developer: "Ubisoft Montpellier", image: "rayman.png", category: "PlayStation 3", description: "Rayman Origins es un juego de plataformas de desplazamiento lateral con elementos de resolución de puzles. El juego contiene modos para un solo jugador y multijugador, con soporte para 4 jugadores. Los jugadores tendrán el control del héroe principal Rayman, Globox y dos Diminutos."},
  {id: 27, name: "The Elder Scrolls V: Skyrim", price: 1500, developer: "Bethesda", image: "skyrim.png", category: "PlayStation 3", description: "La historia de Skyrim se centra en los esfuerzos del personaje, Dovahkiin (sangre de dragón), para derrotar a Alduin, un dragón/dovah que, según la profecía, destruirá el mundo. La trama está fechada doscientos años después de los sucesos de Oblivion y tiene lugar en la provincia ficticia de Skyrim."},
  {id: 28, name: "Call of Juarez: The Cartel", price: 700, developer: "Techland", image: "callofjuarez.png", category: "PlayStation 3", description: "En este juego regresan las luchas con puños de Call of Juarez, utilizados solo contra guardias. El jugador puede robar objetos durante una misión, como móviles o billeteras, lo que desbloquea secretos, pero que puede alertar a sus compañeros si es descubierto."},
  {id: 29, name: "Resistance 3", price: 600, developer: "Insomniac Games", image: "resistance.png", category: "PlayStation 3", description: "Un gran invierno está azotando el país, cuya fuente de origen está en Nueva York, y deberemos viajar hasta allí para destruir esta amenaza y así poder tener algo de esperanza para los pocos supervivientes que quedan y nuestra propia familia. Un Resistance más íntimo, oscuro, desesperado y por momentos terrorífico."},
  {id: 30, name: "inFamous 2", price: 800, developer: "Sucker Punch Productions", image: "infamous.png", category: "PlayStation 3", description: "Culpado por la destrucción de Empire City, considerado como el demonio de esta ciudad y derrotado por la Bestia, Cole huye a New Marais (donde fue creada la esfera del rayo) en busca del científico Dr. Sebastián Wolf para descubrir la clave para aumentar sus poderes y derrotar a La Bestia."},
  {id: 31, name: "Assassins creed 2", price: 2000, developer: "Ubisoft", image: "ac2.png", category: "PlayStation 3", description: "El juego es una secuela directa de Assassin's Creed, que se enfoca en la historia de Desmond Miles después de escapar de los laboratorios de Abstergo con la ayuda de Lucy Stillman, Asesina infiltrada en Abstergo. Intentando destruir a Abstergo y a los Templarios actuales, Desmond es conectado a un Animus creado por los Asesinos de forma independiente a los de Abstergo, para así, revivir las memorias de otro de sus ancestros, Ezio Auditore da Firenze, que vivió en Italia durante el Renacimiento. El jugador pasara de controlar a Desmond para presenciar como Ezio se une a la hermandad, después de que su familia fuese traicionada, en posición de eliminar a aquellos que tienen o tuvieron que ver con la muerte de sus familiares. Mientras se controla a Ezio, el jugador puede explorar areas y ciudades claves de Italia, realizando acciones variadas de acción, sigilo y un modo de juego económico."},
  {id: 32, name: "Mafia 2", price: 1400, developer: "2K Czech", image: "mafia.png", category: "PlayStation 3", description: "El protagonista es Vito Scaletta, un joven siciliano hijo de padres inmigrantes de Sicilia que vuelve a casa tras su involuntario paso por la guerra por cometer un delito. Al llegar a Empire Bay, Joe Barbaro, su amigo de infancia le recibe, y comienza a introducirle en los peligrosos circuitos de la mafia."},
  {id: 33, name: "Borderlands 2", price: 400, developer: "Gearbox Software", image: "borderlands.png", category: "PlayStation 3", description: "El juego se sitúa 5 años después de su anterior título Borderlands. Jack el guapo, antagonista principal, ha tomado la corporación Hyperion, y se ha autoproclamado dictador de Pandora tras haber encontrado La Cámara. El nuevo grupo viaja en tren en busca de La Cámara."},
  {id: 34, name: "Grand Theft Auto V", price: 2200, developer: "RockStar Games", image: "gtav.png", category: "PlayStation 3", description: "Michael, Trevor, Brad y otro compañero junto a Lester eran un grupo de atracadores a gran escala que operaban por todo Estados Unidos y Canada realizando golpes millonarios. Nuestra historia empieza en Ludendorff en el estado de North Yankton. Allí, los atracadores roban un banco y son perseguidos por la policía. Cuando estan escapando, un francotirador abate a Brad de una bala y al intentar ayudarlo, Michael queda herido y al darse a si mismo por muerto, le dice a Trevor que escape con el dinero. No obstante, sobrevive y es arrestado por el FBI. Estos le dicen que si colabora para detener a otros atracadores le liberaran y le incluíran en el programa de protección de testigos y que tendrá una vida de lujos. Él accede a cambio de que le den una vida nueva y que falseen su muerte y así lo hacen."},
  {id: 35, name: "Darksiders", price: 1200, developer: "Vigil Games", image: "darksiders.png", category: "PlayStation 3", description: "La serie se desarrolla en una Tierra post-apocalíptica, donde la humanidad se ha extinguido y los ángeles y los demonios luchan por el control del mundo. Entre ellos se encuentran los Cuatro Jinetes del Apocalipsis, los últimos de los Nephilim que tienen la tarea de equilibrar el orden."},
  {id: 36, name: "Dark Souls", price: 2500, developer: "FromSoftware", image: "darksouls.png", category: "PlayStation 3", description: " es el nuevo juego de rol y acción de los creadores de Demon's Souls, FromSoftware. Dark Souls cuenta con muchos elementos ya conocidos: un universo fantástico y oscuro, tortuosos recorridos por mazmorras, temibles enemigos e interacciones online exclusivas."},

  //                                                                                Windows

  {id: 37, name: "Wolfenstein 2009", price: 300, developer: "Id Software & Raven Software", image: "wolf.png", category: "Windows", description: " A fines de 1943, tras el fracaso de la Operación Resurrección, los nazis descubren una fuente de poder en la forma del velo, una dimensión misteriosa que se puede manipular con los cristales que se encuentran en la ciudad de Isenstadt."},
  {id: 38, name: "Crysis", price: 700, developer: "Crytek", image: "crysis.png", category: "Windows", description: "En el año 2020, un artefacto aparece enterrado en una isla del Mar de Filipinas. El grupo de científicos enviado para investigar resulta desaparecido y sin contacto. Por ello, el gobierno norcoreano ha decretado la prohibición de entrada a la zona para futuras investigaciones. No obstante, los Estados Unidos ha enviado un grupo militar de élite llamado Equipo Raptor para reconocer la zona e informar al Pentágono de lo que ocurre."},
  {id: 39, name: "Grand Theft Auto IV + Episodes from Liberty city", price: 1200, developer: "RockStar Games", image: "gtaiv.png", category: "Windows", description: "El protagonista de la trama es Niko Bellic, un veterano de guerra de Europa del Este, que emigró a Estados Unidos en busca del sueño americano prometido por su primo, pero que rápidamente es arrastrado a un submundo criminal."},
  {id: 40, name: "Metro 2023", price: 400, developer: "4A Games", image: "metro.png", category: "Windows", description: "La historia tiene lugar en un Moscú postapocalíptico, mayoritariamente dentro del sistema del metro de la capital, donde el protagonista fue criado, pero ocasionalmente el jugador debe ir a la superficie para completar misiones o conseguir munición."},
  {id: 40, name: "Dark Souls - Prepare to die", price: 4200, developer: "FromSoftware", image: "darksoulswindows.png", category: "Windows", description: "Nuevos mapas y entornos; nuevos jefes finales, enemigos y personajes no jugables; un arsenal de nuevas armas y armaduras; y contenido de desafíos adicionales para que los afronten los héroes más curtidos en su regreso al mortífero mundo de Lordran"},
  {id: 42, name: "Fallout 3", price: 700, developer: "Bethesda", image: "fallout.png", category: "Windows", description: "Fallout 3 se desarrolla en el año 2277, 36 años después de los sucesos de Fallout 2 y 200 años después del apocalipsis nuclear que devastó el mundo del juego en un futuro donde los conflictos internacionales con China culminaron en una guerra chino-estadounidense en la segunda mitad del siglo XXI."},
  {id: 43, name: "Fallout New Vegas", price: 845, developer: "Obsidian Entertainment", image: "falloutnv.png", category: "Windows", description: "Fallout: New Vegas tiene lugar durante el año 2281, cuatro años después de los sucesos de Fallout 3 y 204 años después de la Gran Guerra de 2077, estableciendo el contexto del juego como el más tardío de toda la saga. El juego se sitúa en la ciudad de New Vegas —una post-apocalíptica Las Vegas— y en el Desierto de Mojave. A diferencia de la mayoría de ciudades presentadas a lo largo de la saga, Las Vegas no recibió un ataque nuclear directo; los edificios permanecen intactos y la mutación de sus habitantes es mínima."},
  {id: 44, name: "Half life 2", price: 200, developer: "Valve", image: "hl2.png", category: "Windows", description: "Un shooter en primera persona que transcurre dos décadas después de la historia del primer Half Life. Gordon Freeman despierta de su estado de hibernación y se convierte en el símbolo de la resistencia humana frente a la Alianza. Acción en una aventura cuya historia profundiza mucho más allá del conflicto."},
  {id: 45, name: "Just Cause 2", price: 150, developer: "Avalanche Studios & Eidos Interactive", image: "justcause2.png", category: "Windows", description: "La acción, así como la trama, se desarrolla en el ficticio archipiélago paradisíaco de Panau. El protagonista es, de nuevo, Rico Rodríguez, el agente más calificado y peligroso de la Agencia, que es enviado a Panau para eliminar a un agente disidente refugiado en la isla."},
  {id: 46, name: "F.E.A.R 2", price: 600, developer: "Monolith Productions", image: "fear2.png", category: "Windows", description: "La secuela de F.E.A.R. continúa la historia del ser sobrenatural, Alma Wade, cuya rabia contra los que le hicieron daño empezó una escalada de la crisis paranormal que amenaza con devorar y sustituir la realidad con la suya. En vez de jugar como el Hombre Punta, el protagonista del juego es Michael Becket, un operador del equipo Delta Force que es enviado para detener a Genevieve Aristide aproximadamente treinta minutos antes del final de F.E.A.R."},
  {id: 47, name: "Devil May Cry 4", price: 700, developer: "Capcom", image: "dmc4.png", category: "Windows", description: "La historia sigue a Nero, un adolescente que posee poderes demoníacos que se encuentra en una misión para detener al personaje principal de la serie, Dante, después de que este asesinara a varios miembros de la Orden de la Espada incluyendo a su líder."},
  {id: 48, name: "Halo 2", price: 300, developer: "Bungie Studios", image: "halo2.png", category: "Windows", description: "Halo 2 es la secuela del mítico shooter de Bungie lanzado en exclusiva para Xbox. Esta segunda entrega narra los combates del Jefe Maestro y de El Inquisidor, cada uno perteneciente a un bando distinto."},

  //                                                                                Xbox One

  {id: 49, name: "GEAR 5", price: 2500, developer: "The Coalition", image: "gear.png", category: "Xbox One", description: "La dependencia que tienen los seres humanos en la tecnología se ha convertido en su perdición y los enemigos se unen para destruir todos los supervivientes."},
  {id: 50, name: "Red dead Redemption 2", price: 3600, developer: "RockStar Games", image: "rdr2.png", category: "Xbox One", description: "Después de que un atraco en el pueblo de Blackwater sale muy mal, Arthur Morgan y la banda Van der Linde se ven obligados a huirse. Con agentes federales y los mejores cazarrecompensas persiguiéndolos, la banda debe robar, atracar y luchar por el duro corazón de Estados Unidos para sobrevivir."},
  {id: 51, name: "Halo Infinite", price: 5000, developer: "343 Industries", image: "halo.png", category: "Xbox One", description: "El jefe Maestro el gran héroe de la humanidad y personaje principal de la saga se enfrentara a un grupo sanguinario y temible que alguna vez fueron parte del Covenant llamados los Desterrados, estos fueron integrados desde Halo Wars 2 y en las novelas del universo de Halo, ahora debutando como la amenaza principal en Halo Infinite."},
  {id: 52, name: "Far Cry 6", price: 3500, developer: "Ubisoft", image: "farcry.png", category: "Xbox One", description: "El juego se desarrolla en Yara, una isla caribeña ficticia que yace bajo una dictadura liderada por El Presidente Antón Castillo quien está preparando a su hijo, Diego, para que continúe con su mandato. El jugador encarna al guerrillero Dani Rojas, quien busca derrocar a Castillo y a su régimen."},
  {id: 53, name: "Call of duty Modern Warfare", price: 6500 , developer: "Infinity Ward", image: "codmw.png", category: "Xbox One", description: "Cuenta la historia de un país en guerra, el nacimiento de milicias y grupos terroristas, unos rusos malévolos, y un heroico grupo de soldados de varios países que trata de limpiar el desastre que resulta de todo lo que describimos arriba."},
  {id: 54, name: "Call of duty Black Ops-Cold War", price: 5500, developer: "Treyarch & Raven Software", image: "codbcw.png", category: "Xbox One", description: "En 1981, el presidente de los Estados Unidos, Ronald Reagan, encargó al agente de la CIA Russell Adler que cazara al agente soviético Perseo para evitar un ataque al mundo. Adler reúne a un equipo de élite de operativos que incluye a Bell con la ayuda de Alex Mason, Frank Woods y Jason Hudson."},
  {id: 55, name: "The Witcher 3", price: 1500, developer: "CD Projekt RED", image: "witcher.png", category: "Xbox One", description: "Es un juego de perspectiva en tercera persona, el jugador controla al protagonista Geralt de Rivia, un cazador de monstruos conocido como Lobo Blanco, es un brujo, el cual emprende un largo viaje a través de Los reinos del norte."},
  {id: 56, name: "Cyberpunk 2077", price: 1500, developer: "CD Projekt RED", image: "cyber.png", category: "Xbox One", description: "Narra la historia de David Martínez, un adolescente que, tras sufrir una tragedia personal, decide tomar las riendas de su vida y adentrarse en los implacables bajos fondos de Night City."},
  {id: 57, name: "Dishonored 2", price: 1200, developer: "Arkane Studios", image: "dishonored.png", category: "Xbox One", description: "Dishonored 2 es un juego de acción-aventura y sigilo en primera persona. El jugador puede iniciar la campaña con Emily Kaldwin o Corvo Attano (protagonista de Dishonored) los cuales podrán expresarse a lo largo del juego. Ambos personajes tendrán habilidades y estilos de juego muy distintos."},
  {id: 58, name: "Assassins Creed Valhalla", price: 3200, developer: "Ubisoft", image: "acvalhalla.png", category: "Xbox One", description: "Es un RPG de acción ambientado durante la invasión vikinga de Inglaterra. Los jugadores tendrán la oportunidad de encarnar al líder de un clan nórdico que ha sido expulsado de Noruega durante las primeras horas del juego y que decide asentarse en Inglaterra para empezar una nueva vida."},
  {id: 59, name: "Monster Hunter World", price: 5000, developer: "Capcom", image: "monsterhunter.png", category: "Xbox One", description: "Monster Hunter World es el retorno de la serie a las consolas de sobremesa, permitiéndonos cazar criaturas gigantes en un entorno salvaje, ya sea en solitario o con tres cazadores con un nuevo sistema multijugador drop-in que permite cooperativo entre regiones."},
  {id: 60, name: "Residente Evil 7", price: 2500, developer: "Capcom", image: "residentevil7.png", category: "Xbox One", description: "Este es un juego de survival-horror en el que los jugadores asumen el papel de Ethan, un hombre en busca de su esposa desaparecida en una mansión abandonada. Desde una perspectiva en primera persona con arma de fuego realista, gritos de dolor, y exagerados efectos de la salpicadura de sangre. A medida que los jugadores avanzan a través de la historia, escenas pueden representar casos de actos de gore e intensa de violencia: el brazo de un personaje desmembrado por una motosierra; pierna de un hombre cortado por la rodilla con una pala; un personaje empalado a través de la cara con una pala. Algunas áreas también muestran cuerpos mutilados que expuesta órganos/vísceras. Las palabras joder y mierda se escuchan en el diálogo."},
];

const storegamesLS = (games) => {
  localStorage.setItem("games", JSON.stringify(games));
}

const loadgamesLS = () => {
  return JSON.parse(localStorage.getItem("games")) || [];
}

storegamesLS(games);
